### ISSUE TITLE
tracker page

### ISSUE THREAD

**Issue by chelsey-g** [chelsey-g/fitness-app#21]
- [x]  cannot add decimal point into tracker
- [x] once you submit, page does not route to weight history
- [x]  fix delete weight to modal to confirm delete
